In [ ]:
#Mercedes project
import numpy as np 
import pandas as pd
import matplotlib.pyplot as pl

In [ ]:
cd

/root

In [ ]:
cd /content/sample_data

/content/sample_data

In [ ]:
#Fetch train data
x_train = pd.read_csv('train.csv')

In [ ]:
x_train.head(3)

   ID       y  X0 X1  X2 X3 X4  ... X378 X379 X380  X382  X383  X384  X385
0   0  130.81   k  v  at  a  d  ...    0    0    0     0     0     0     0
1   6   88.53   k  t  av  e  d  ...    0    0    0     0     0     0     0
2   7   76.26  az  w   n  c  d  ...    0    0    0     1     0     0     0

[3 rows x 378 columns]

In [ ]:
#Fetch test data
x_test = pd.read_csv('test.csv')

In [ ]:
x_test.head(3)

   ID  X0 X1  X2 X3 X4 X5 X6  ... X377  X378  X379  X380  X382  X383  X384  X385
0   1  az  v   n  f  d  t  a  ...    0     1     0     0     0     0     0     0
1   2   t  b  ai  a  d  b  g  ...    1     0     0     0     0     0     0     0
2   3  az  v  as  f  d  a  j  ...    0     1     0     0     0     0     0     0

[3 rows x 377 columns]

In [ ]:
#Check the dimensions
x_train.shape

(4209, 378)

In [ ]:
x_test.shape

(4209, 377)

In [ ]:
#We can drop the ID column as currently it is not required
x_train.drop("ID",inplace=True, axis=1)

In [ ]:
x_test.drop("ID", inplace=True, axis=1)

In [ ]:
x_test.head(2)

   X0 X1  X2 X3 X4 X5 X6 X8  ...  X377  X378  X379  X380  X382  X383  X384  X385
0  az  v   n  f  d  t  a  w  ...     0     1     0     0     0     0     0     0
1   t  b  ai  a  d  b  g  y  ...     1     0     0     0     0     0     0     0

[2 rows x 376 columns]

In [ ]:
#Need to check for Zero variance column and if available they should be dropped.
zero_var = x_train.var()[x_train.var() == 0].index.values
zero_var

array(['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290',
       'X293', 'X297', 'X330', 'X347'], dtype=object)

In [ ]:
 x_train.drop(zero_var, inplace=True, axis=1)

In [ ]:
x_train.head(2)

        y X0 X1  X2 X3 X4 X5 X6  ... X377  X378  X379  X380  X382  X383  X384  X385
0  130.81  k  v  at  a  d  u  j  ...    1     0     0     0     0     0     0     0
1   88.53  k  t  av  e  d  y  l  ...    0     0     0     0     0     0     0     0

[2 rows x 365 columns]

In [ ]:
 x_test.drop(zero_var, inplace=True, axis=1)

In [ ]:
x_test.head(2)

   X0 X1  X2 X3 X4 X5 X6 X8  ...  X377  X378  X379  X380  X382  X383  X384  X385
0  az  v   n  f  d  t  a  w  ...     0     1     0     0     0     0     0     0
1   t  b  ai  a  d  b  g  y  ...     1     0     0     0     0     0     0     0

[2 rows x 364 columns]

In [ ]:
#Check if any null values exist.
np.sum(x_train.isnull().sum())

0

In [ ]:
x_train.shape

(4209, 365)

In [ ]:
x_train.shape

(4209, 365)

In [ ]:
x_train.isnull().sum()

y       0
X0      0
X1      0
X2      0
X3      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 365, dtype: int64

In [ ]:
#check if any columns which are not numeric
x_train.describe(include=['object'])

          X0    X1    X2    X3    X4    X5    X6    X8
count   4209  4209  4209  4209  4209  4209  4209  4209
unique    47    27    44     7     4    29    12    25
top        z    aa    as     c     d     w     g     j
freq     360   833  1659  1942  4205   231  1042   277

In [ ]:
x_val = x_train.describe(include=['object']).columns.values

In [ ]:
x_val

array(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype=object)

In [ ]:
#label Encoder
from sklearn.preprocessing import LabelEncoder

In [ ]:
y_val = x_test.describe(include=['object']).columns.values
y_val

array(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype=object)

In [ ]:
#Apply label Encoder for the columns which are not numeric. DO it for both train & test data set.
 le = LabelEncoder()

In [ ]:
for i , val in enumerate(list(x_val)):
 if(x_train[val].dtype in [object]):
    x_train[val]=le.transform(x_train[val])    
    le.fit_transform(x_train['X0'])

In [ ]:
np.unique(x_train['X5'].values)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [ ]:
x_test.head()

   X0 X1  X2 X3 X4 X5 X6 X8  ...  X377  X378  X379  X380  X382  X383  X384  X385
0  az  v   n  f  d  t  a  w  ...     0     1     0     0     0     0     0     0
1   t  b  ai  a  d  b  g  y  ...     1     0     0     0     0     0     0     0
2  az  v  as  f  d  a  j  j  ...     0     1     0     0     0     0     0     0
3  az  l   n  f  d  z  l  n  ...     0     1     0     0     0     0     0     0
4   w  s  as  c  d  y  i  m  ...     0     0     0     0     0     0     0     0

[5 rows x 364 columns]

In [ ]:
np.unique(x_train['X0'].values)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46])

In [ ]:
for i , val in enumerate(list(x_test.columns)):
  if(x_test[val].dtype in [object]):
    x_test[val]=le.fit_transform(x_test[val])
le.fit_transform(x_test['X0'])

array([21, 42, 21, ..., 47,  7, 42])

In [ ]:
#PCA
from sklearn.decomposition import PCA

In [ ]:
x_train.head()

        y  X0  X1  X2  X3  X4  X5  ...  X378  X379  X380  X382  X383  X384  X385
0  130.81  32  23  17   0   3  24  ...     0     0     0     0     0     0     0
1   88.53  32  21  19   4   3  28  ...     0     0     0     0     0     0     0
2   76.26  20  24  34   2   3  27  ...     0     0     0     1     0     0     0
3   80.62  20  21  34   5   3  27  ...     0     0     0     0     0     0     0
4   78.02  20  23  34   5   3  12  ...     0     0     0     0     0     0     0

[5 rows x 365 columns]

In [ ]:
#Reduce the data set and retain the required columns using PCA
pcaModel = PCA(n_components=12,svd_solver='full')
pcaModel
#We can remove column y from our training data set as the values are already availble for test.
train_df = x_train.drop('y', axis=1) 
test_df=x_train['y']

In [ ]:
pcaModel.fit(train_df)

PCA(copy=True, iterated_power='auto', n_components=12, random_state=None,
    svd_solver='full', tol=0.0, whiten=False)

In [ ]:
pcaModel.n_components_
#pca.explained_variance_ratio_

12

In [ ]:
#Below array comprises of 98% variance if we sum it up.
pcaModel.explained_variance_ratio_

array([0.38334782, 0.21388033, 0.13261866, 0.11826642, 0.09206008,
       0.01590604, 0.0074454 , 0.00433701, 0.00294021, 0.00241796,
       0.00236488, 0.00203229])

In [ ]:
#Split to get training and validation data
from sklearn.model_selection import train_test_split
X_train, X_val, Y_train, Y_val = train_test_split(train_df, test_df, test_size=0.2, random_state=42)

In [ ]:
X_train

      X0  X1  X2  X3  X4  X5  X6  ...  X378  X379  X380  X382  X383  X384  X385
1006  34  23  16   2   3   6  10  ...     0     0     0     0     0     0     0
1840  35  20  16   3   3   4   6  ...     0     0     0     0     0     0     0
3792  27   4  33   2   3  25   8  ...     0     0     0     0     0     0     0
152   31   1  27   3   3  13   8  ...     0     0     0     0     0     0     0
1557  19  10  16   2   3   3  11  ...     0     0     0     0     0     0     0
...   ..  ..  ..  ..  ..  ..  ..  ...   ...   ...   ...   ...   ...   ...   ...
3444  31  10  16   2   3  22  11  ...     0     0     0     0     0     0     0
466   20  25  25   2   3   9   9  ...     0     0     0     1     0     0     0
3092  45  24   3   2   3  21   8  ...     0     0     0     0     0     0     0
3772  45  19   8   5   3  25   8  ...     0     0     0     0     0     0     0
860   22   1   7   2   3   5   9  ...     0     0     0     0     0     0     0

[3367 rows x 364 columns]

In [ ]:
Y_train.head(2)

1006    88.96
1840    89.90
Name: y, dtype: float64

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
 pca_X_train = pd.DataFrame(pcaModel.transform(X_train))

In [ ]:
pca_X_train.describe()

                0            1   ...           10           11
count  3367.000000  3367.000000  ...  3367.000000  3367.000000
mean     -0.033240    -0.197852  ...     0.000271    -0.002140
std      14.263326    10.599765  ...     1.123743     1.029313
min     -21.899802   -21.151050  ...    -3.054352    -2.267402
25%     -11.827716    -7.337372  ...    -0.778877    -0.619578
50%      -3.838910    -2.602931  ...    -0.046605    -0.097367
75%      11.588808     5.303114  ...     0.735884     0.448439
max      34.764631    30.136712  ...     3.525782     4.434044

[8 rows x 12 columns]

In [ ]:
#Transform pca_X_val (validation data) in the model
pca_X_val = pd.DataFrame(pcaModel.transform(X_val)) 
pca_X_val

            0          1          2   ...        9         10        11
0    17.841395 -15.245960  -6.299416  ... -0.030686  2.001232 -1.150132
1    -0.990921 -15.208289   1.040124  ... -0.235359 -1.169911 -1.613507
2    -2.894524   3.927628  -1.575664  ...  0.334843  0.750981  0.627861
3    13.849039   1.874404   6.003682  ... -0.629472 -0.526549  4.061894
4    20.639205 -15.373246   6.846871  ... -0.183061  0.120290 -1.590133
..         ...        ...        ...  ...       ...       ...       ...
837 -11.291745  19.029773  -6.784557  ... -0.773530 -0.667633 -1.192638
838  -8.140382  17.085313   7.767719  ... -1.771242  0.254006 -1.809658
839 -16.952539   7.863151  -8.961566  ...  0.148487  0.498303  0.674981
840   1.756738 -14.990083  13.314169  ... -1.435857 -0.297580 -0.094077
841 -10.289994   2.836025  10.100763  ...  1.113111 -0.349639 -0.781620

[842 rows x 12 columns]

In [ ]:
#Transform pca_X_Test(testing data) in the model
pca_X_test = pd.DataFrame(pcaModel.transform(x_test)) 
pca_X_test

             0          1          2   ...        9         10        11
0     15.122597  12.426344  16.575688  ... -0.875308 -1.659406  3.631911
1    -16.418523  -6.087805  -5.818108  ...  0.856518  0.115282 -0.170789
2     11.310890  -2.240987  -5.683210  ... -0.115722 -0.926723  3.312713
3     12.883278  13.284800  14.409574  ... -1.443821 -1.820858  3.921842
4    -12.119759   3.021287  20.739083  ...  0.091997  0.324546  0.215057
...         ...        ...        ...  ...       ...       ...       ...
4204  22.045696  -5.791779 -14.969442  ... -0.162767 -0.083598 -0.247976
4205 -16.799934  -5.849004 -13.362178  ...  0.400394  0.367185  0.955280
4206 -13.467664   3.524155  -0.387634  ...  0.676011 -0.077011 -0.264892
4207  24.086925  -6.512201  -6.389509  ... -0.442047  1.035506 -0.069206
4208 -16.557942  -5.495652 -13.703891  ...  0.637375  2.268038  0.519457

[4209 rows x 12 columns]

In [ ]:
#Building XGBOOST model for linear regression
import xgboost as xgb 
from sklearn.ensemble import RandomForestRegressor
model = xgb.XGBRegressor(objective='reg:linear', learning_rate=0.1)

In [ ]:
pca_X_train.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 'y'], dtype='object')

In [ ]:
pca_X_train.drop(columns=['y'], inplace= True, axis=1)

In [ ]:
pca_X_train.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], dtype='object')

In [ ]:
#Fit below values in the model
model.fit(pca_X_train.values, Y_train.values)

[15:42:22] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [ ]:
pred_y_val = model.predict(pca_X_val.values)

In [ ]:
#Calculate mean square value
mse_score = mean_squared_error(Y_val,pred_y_val)

In [ ]:
from sklearn.metrics import r2_score
print('Proj R2 score is: ', r2_score(Y_val, pred_y_val))

Proj R2 score is:  0.4537282860932641